### PR TITLE
add index.html, style.css to git+GitHub Tinkering page [#160125675]

### PR DESCRIPTION
**Pull request by sekayasin**
## add index.html and style.css 
index.html has plain text not formatted per html syntax 
style.css has no rules

### CODE REVIEW

**Comment by mariamiah** [comment]
good work

**Comment by okellogabrielinnocent** [comment]
Nice work

**Review by okellogabrielinnocent — APPROVED** [review]

**Comment by SokoPaulSokool** [comment]
great work

**Comment by trekab** [comment]
Nice!

**Pull request merged**
